### ISSUE TITLE
Sort materials by alphabetical order?

### ISSUE THREAD

**Issue by 130N1D** [ChrisHinde/MaterialUtilities#11]
What happened to the alphabetical material sort function? Are you going to bring it back?
https://imgur.com/a/4hZ3A0O

**Comment by EugeneDudavkin** [comment]
Hello,
its an additional addon for this addon
see here
https://blenderartists.org/t/how-to-sort-all-materials-on-object/702866/7

**Comment by ChrisHinde** [comment]
This was never a part of MaterialUtilities (or the MaterialUtils addon for 2.5x).
I could add this if it's truly requested, but since there already is an add-on that does it (and that I'm aware of) I'm not too keen to add the functionality.

**Comment by Wolfgang-IX** [comment]
just to add, Blender already has this feature
![image](https://github.com/ChrisHinde/MaterialUtilities/assets/47208316/31dbae26-fd87-4f44-ad34-dceb87b41659)
