### ISSUE TITLE
Merge Multiple Materials

### ISSUE THREAD

**Issue by tcoursey** [ChrisHinde/MaterialUtilities#13]
I'm trying to use this add-on to merge the following materials.

Metal_Alum_Brushed_56
Metal_Alum_Brushed_57
Metal_Alum_Brushed_58
Metal_Alum_Brushed_59
Metal_Alum_Brushed_60

I'm guessing one could use the REGEX pattern, but I have no idea what pattern or values to put in there.

If this is possible with what is available in the addon, can someone show me how...otherwise would it be possible to implement an option where you select a material and on the pattern option it TRUNCATES or combines all the materials that match except for the last characters...

So in the above example you could select Metal_Alum_Brushed_56 and put in the new special pattern option 3 and all the materials that end with _56 _57 etc...would become Metal_Alum_Brushed.

I hope that makes sense.  Would love to see this!

**Comment by ChrisHinde** [comment]
Sorry for the late response (I don't get any e-mails from GH when these come in, and I forget to check)

If you have v2.3.0 or newer there's both an RegEx option and a just a "Define Delimiter" option for Merge Base Names.
In this case the latter option would work just fine, just change it from `.` to `_` in the Delimiter input field

As for RegEx, the expression should be `^%BASE_NAME_(\d{1,3})$` or `^(.*)_(\d{1,3})$`, but there seems to be a bug related to custom patterns, so if you use a RegEx like this you'd need to change one material name manually (so there exists a material called `Metal_Alum_Brushed`) before running the tool.
