### ISSUE TITLE
No option to remove version 2.2.0

### ISSUE THREAD

**Issue by Giga-999** [ChrisHinde/MaterialUtilities#14]
![Screenshot 2023-11-18 093645](https://github.com/ChrisHinde/MaterialUtilities/assets/151394341/658aa441-4bb9-4333-b0b6-988917ca21d4)
The title pretty much says it all.  No option to remove and no folders to delete in appdata.

**Comment by ChrisHinde** [comment]
Built-in addons, like 2.2.0, doesn't have a Remove option (this is a "Blender thing", and not up to the addons, eg. https://chris.hindefjord.se/wp-content/uploads/2023/11/Skarmbild-2023-11-18-193144.png ).

Similarly, built-in addons live under the app installation directory, not in the AppData directory (as you can see in the path under "File:").
Generally there is no reason to remove the built-in addon, just disable it, and enable the manually installed one ( https://chris.hindefjord.se/wp-content/uploads/2023/11/Skarmbild-2023-11-18-192908.png ).
If you still want to remove it, you have to do so from the application directory (NB: it will be back if you reinstall/update)
