### ISSUE TITLE
the add-on crashes, if you have multiple objects and e.g. splines have no materials

### ISSUE THREAD

**Issue by luckychris** [ChrisHinde/MaterialUtilities#17]
**Describe the bug**

**To Reproduce**
1. Select several objects, some with materials, some without materials (in my case the splines didn't have materials)
2. shift-q -> clean slots -> clean material slots
3. click here: 
<img width="299" alt="image" src="https://github.com/user-attachments/assets/8168225b-1465-47b6-988d-58220485ef37">

to enable it for all objects
-> error

<img width="782" alt="image" src="https://github.com/user-attachments/assets/c402215f-0140-4384-a10c-00cf36c8b2c9">

the error happened in line 483 (i reproduced that error with my lines, but just commented - sorry for that)

i was able to repair the error by this:

in **functions.py**:

    for obj in objects:
          used_mat_index = []  # we'll store used materials indices here
          assigned_materials = []
          material_list = []
          material_names = []
  
          materials = obj.material_slots.keys()
  
          if len(materials) == 0: # my code
              continue            # my code
  
          if obj.type == 'MESH':
              # check the polygons on the mesh to build a list of used materials
              mesh = obj.data

maybe you find a better solution, but for me it worked.

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Blender version and build [e.g Blender 2.80 (sub 74), branch: master, commit date: 2019-07-11 13:50 hash:]
 - Add-on Version [e.g. 1.0.3]

**Additional context**

**Comment by ChrisHinde** [comment]
Thanks for the report and code.
This should now be fixed (there also is an small update to the operator [Clean Material Slots]) in the latest version (v3.0.2)
