### ISSUE TITLE
Added keymap doesnt seem to work [2.2.2]

### ISSUE THREAD

**Issue by schroef** [ChrisHinde/MaterialUtilities#19]
**Describe the bug**
When activating the add-on, it adds a keymap to " bpy.context.window_manager.keyconfigs.addon", on my system using bl4.1.1 this doesnt seem to work,. I when i changed it to " bpy.context.window_manager.keyconfigs.user" the shortcut does work

**To Reproduce**
1. Activate the addon
2. Add cube and simple material
3. Try using the shortcut; Shift+Q

**Expected behavior**
A working shortcut in the 3dView

**Screenshots**
![Screenshot 2024-11-11 102215](https://github.com/user-attachments/assets/744daf0f-be2b-4009-a133-8a563cc47d62)

**Versions (please complete the following information):**
 - version: 4.1.1, branch: blender-v4.1-release, commit date: 2024-04-15 15:11, hash: e1743a0317bc, type: Release
build date: 2024-04-15, 23:33:30
platform: 'Windows-10-10.0.26120-SP0'
 - V2.2.2

**Additional context**

**Comment by ChrisHinde** [comment]
I can't seem to reproduce this issue; I downloaded the latest version (4.2.3), and tried with both the Extensions version, and local version of MaterialUtilites.

User vs Addon keyconfigs shouldn't really matter (although the addon context is more appropriate).

I have some questions:

1. Did you get any error messages (either in the "Info panel" [bottom left in the Scripting view], or the Console [Window > Toggle System Console])
2. Do you have any other addons installed/enabled that could interfere??
3. Is it on a "clean"/new install? Have you used the addon earlier with this version of Blender, or an earlier one?
(4. Could you run `bpy.context.window_manager.keyconfigs.addon.keymaps['3D View'].keymap_items.keys()` in the Python console, without and with the addon enabled, and post the result?)

I'd recommend to try the later version of the addon (from GitHub), and perhaps also a newer version of Blender.

**Comment by schroef** [comment]
I tried looking at keymap, but there is nothing. Ill try again. 
I did see my keymap act strange. Where everything in 3dView(Global) gets cleared, with just one shortcut there. 
I didnt see any errors, if i recall properly. Let me try it again. Ill revert the code and restart

**Comment by schroef** [comment]
Okay weird, now i also see it work properly. I did try it could times. Perhaps it was also due to the other issue i described where my complete keymap for 3dview got cleared

**Comment by ChrisHinde** [comment]
Glad to here that it works now, and hope it keeps working.
