### ISSUE TITLE
Menu "VIEW3D_MT_materialutilities_main" not found

### ISSUE THREAD

**Issue by xan2622** [ChrisHinde/MaterialUtilities#7]
**Describe the bug:**
After disabling the addon, if Shift+Q is pressed, this error appears:
`Menu "VIEW3D_MT_materialutilities_main" not found`

**Steps to reproduce the behavior:**
1- Go to *Preferences > Addons*
2- Disable the addon (untick the checkbox)
3- In the Viewport, press the *Shift+Q* hotkey

**Expected behavior**
Once the addon disabled, there shouldn't be any error poping up.

**Screenshots**
![Annotation 2020-04-07 210355](https://user-images.githubusercontent.com/1732773/78709575-2aa53b80-7914-11ea-83bd-14806591dd0f.jpg)

![Annotation 2020-04-07 210356](https://user-images.githubusercontent.com/1732773/78709577-2b3dd200-7914-11ea-8e80-df4b8ae305ca.jpg)

**Versions:**
Blender 2.82a (Official)_ and_Blender 2.83 Daily Build (blender-2.83-505a19ed75b2-windows64)
Addon version: 2.2.0 beta

**Additional context**
Could it be a problem with my custom hotkeys?
[perso_hotkeys.zip](https://github.com/ChrisHinde/MaterialUtilities/files/4446618/perso_hotkeys.zip)

**Comment by hced** [comment]
Sorry for bumping this but in Blender 3.2.0 I get the same issue.
